version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/vinyguedess/creamcore

    environment:
      DEBUG: 0
      DB_DRIVER: sqlite
      DB_NAME: creamcore.sqlite3
      TEST_RESULTS: coverage

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Prepare environment
          command: |
            mkdir -p $TEST_RESULTS

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            make install

      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            make test
            ./cc-test-reporter after-build -t gocov --exit-code $?

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts:
          destination: $TEST_RESULTS
          path: $TEST_RESULTS
